# Generated by Django 4.2.3 on 2023-07-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentru',
            name='number_views',
            field=models.IntegerField(default=0, verbose_name='просмотры'),
        ),
        migrations.AlterField(
            model_name='blogentru',
            name='publication_attribute',
            field=models.BooleanField(default=True, verbose_name='признак публикации'),
        ),
    ]
