# Generated by Django 4.2.3 on 2023-07-28 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_number_views_alter_blogentry_number_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='number_views',
        ),
    ]
