# Generated by Django 4.2.3 on 2023-07-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_product_number_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_views',
            field=models.IntegerField(default=0, verbose_name=' number_views'),
        ),
        migrations.AddField(
            model_name='product',
            name='publication_attribute',
            field=models.BooleanField(default=True),
        ),
    ]
