# Generated by Django 4.2.3 on 2023-07-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='number_views',
            field=models.IntegerField(default=2, verbose_name=' number_views'),
        ),
    ]
