# Generated by Django 4.2.3 on 2023-07-28 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_blogentry_number_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogEntry',
        ),
    ]
