# Generated by Django 4.2.3 on 2023-08-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_version_name_current_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='name_current_version',
            field=models.CharField(max_length=150, verbose_name='признак текущей версии'),
        ),
    ]
