# Generated by Django 4.2.3 on 2023-08-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_version_name_current_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='number_version',
            field=models.IntegerField(default=0, verbose_name='number_version'),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_views',
            field=models.IntegerField(default=0, verbose_name='number_views'),
        ),
    ]
