# Generated by Django 4.2.3 on 2023-08-13 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_version_number_version_alter_product_number_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='name_current_version',
            field=models.BooleanField(default=False, verbose_name='name_current_version'),
        ),
        migrations.AlterField(
            model_name='version',
            name='number_version',
            field=models.IntegerField(default=1, verbose_name='number_version'),
        ),
        migrations.AlterField(
            model_name='version',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ver', to='main.product', verbose_name='product'),
        ),
    ]
